FROM debian:latest

RUN apt-get install update -y
RUN apt-get install build-essential -y
RUN apt-get install make cmake -y
RUN apt-get install valgrind -y
RUN apt-get install nano vim -y
RUN apt-get install netcat -y
RUN apt-get install git -y
